# Training
n_ctx: 4
checkpoint: cholec_vals
log_file: surgadapt+cholec.txt
model_name: clip_gcn
batch_size: 128
lr: 1e-5
epochs: 2
gcn_lr: 0.0005
reweight_p: 0.2
relation_file: cholec/word2vec_similarity_matrix.npy
ratio: 1
parent_n_ctx: 4
parent_ctx_init: a photo of a
child_n_ctx: 4
child_ctx_init: a photo
meta_lr: 0.0005
change_epoch: 1
tau: 0.6
image_size: 224
num_classes: 110
super_labels: cholec/cholec_super_labels.txt
super_labels_index: cholec/cholec_labels_index.npy
child_num: 110
label_file: label_jsons/data1.json
val_sp : True
val_methods : ['pp_map', 'pp_loss', 'sp_loss']
perform_init : False
init_train_file : triplet_train_labels.json
init_val_file : triplet_val_labels.json
init_epochs : 5
init_lr : 1e-5
dir : final_check_train
loss : Hill
use_lfile : False
getitem : False
backbone : ViT-L/14
seed: 68
partial: False
#bert_path : /home/swalimbe/surgvlp_trial/Bio_ClinicalBERT
#vlp_weights : /home/swalimbe/surgvlp_trial/nips_v1.tar


# Testing
ckpt: /home/swalimbe/MMLSurgAdapt/checkpoints/cholec_vals/round300/full_data_pp_wan_seed/pp_map/model-highest.ckpt
test_dir: final_check_test
test_loss: Hill